### ISSUE TITLE
P2:  Can't call vix_utils from Jupyter notebook due to asyncio

### ISSUE THREAD

**Issue by AQuant206** [dougransom/vix_utils#19]
I tried using a Jupyter notebook import values from vix_utils to print a term structure though it won't work due to asyncio.   Even adding %autowait asyncio did not help.

This is a nice to have IMO.  I was able to work around it by running python from command line, exporting values to a .CSV, then importing those into the Jupyter notebook afterwards.

**Comment by dougransom** [comment]
Grr.  I thought that should work.

**Comment by dougransom** [comment]
I think with the %autowait aysncio% option AND using the asynchronous interfaces to get the data might work because we create a new event loop in the synchronous interfaces and it might blow up jupyter.  

If you have time please try the asynchronous interfaces.   The function names start with async and have the same function signatures as the synchronous ones.



>>> dir(vix_utils)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'append_continuous_maturity_30day', '**async_get_vix_index_histories', 'async_load_vix_term_structure',** 'continuous_maturity', 'continuous_maturity_30day', 'download_vix_futures', 'futures_utils', 'get_vix_index_histories', 'load_vix_term_structure', 'location', 'pivot_cash_term_structure_on_symbol', 'pivot_futures_on_monthly_tenor', 'select_monthly_futures', 'vix_cash_term_structure', 'vix_constant_maturity_weights', 'vix_futures_dates', 'vix_futures_expiry_date_from_trade_date', 'vix_futures_expiry_date_monthly', 'vix_futures_trade_dates_and_expiry_dates']
>>>

if that works it is probably a matter of documentation and better runtime error reporting to guide the developer .

**Comment by AQuant206** [comment]
I will try that out ~early next week.  Thanks!

**Comment by dougransom** [comment]
Hi any success with this?

**Comment by dougransom** [comment]
Example added in this commit https://github.com/dougransom/vix_utils/commit/7983a57fc1e02ea0fa1ca1af3908e57f1da68195.

**Comment by dougransom** [comment]
new release in pypi today too.

**Comment by AQuant206** [comment]
Awesome, Thank-you!
